### PR TITLE
Mg5 development

### PR DESCRIPTION
**Pull request by TimMeadows**
Added MG5 as a new vehicle based on the MG ZS code. MG5 EV is available as a vehicle type
Switched BMS PID to 7E5 for MG
Added TBOX and PEB ID to PIDS list. 
Updated SoC and Range Calculation.

### CODE REVIEW

**Comment by chrisstaite** [comment]
Hi Tim,

I think it would be much better too detect the vehicle type and automatically change the calculations if required since there's barely any changes. In addition, your changes do not build, it seems you may have pointed at some personal repositories?

Thanks, Chris.

**Comment by TimMeadows** [comment]
Hi Chris, 

I'm new to this (first time I have used github!) so happy to work however you/everybody think is best. 

It makes sense to keep the code aligned, but I wasn't sure how to detect it was an MG5, and then how to do things like define the PID constants based on that. 
Was just trying to get to a starting point where I could look to see how to stop the alarm sounding each time it charges - next issue!. 

I did take a copy to a personal repository (I think), but how do I fix the compile issue? 

Thanks - and apologies if I have done this in the wrong way... 

Tim

**Comment by chrisstaite** [comment]
It appears you've added a submodule, but unnecessarily? Presumably it was something your IDE did? You should be able to fix that by deleting the .gitmodules file.

Switching would be easy, but as you say, detecting the car would be the hardest part.  I was hoping to get my hands on an MG5 to figure that out, but I haven't been able to.

Perhaps doing a full PID scan and uploading to our Google Sheet, Mike can come up with a cunning plan.

Thanks!

**Comment by GreyPeter** [comment]
Hi Tim, I'm fairly new to this as well and I followed this guide https://medium.com/@jonathanmines/the-ultimate-github-collaboration-guide-df816e98fb67. You do a new Git Clone. Then create a branch. You can than make your changes and build and test it. This won't effect the current build unit you are ready to push it. When you do push it we can switch to that branch and test it with our vehicles to make sure it all works. Hope this helps

**Comment by GreyPeter** [comment]
You could probably detect the vehicle with the vin

**Comment by TimMeadows** [comment]
> Having a `using namespace` line in a header file is very much recommended against. This can cause all sorts of problems.

Ah, Ok. 
TBH, I was just copying code from the vehicle_none set up so that the uint32_t were not being highlighted. 

What is the proper way to do this? 

Also - am I right in thinking that any commits I make to my repository are automatically updated in this pull request - Like my Tidy Up one?

Thanks

Tim

**Comment by chrisstaite** [comment]
All commits to your repo on the branch that this pull request is from will be automatically updated to it.  The proper way to include the uint types is to `#include <cstdint>`.

**Comment by TimMeadows** [comment]
Thanks Chris, that makes sense. 
Have updated as you suggested...

**Comment by chrisstaite** [comment]
I've tried to merge the two vehicles together.  I've not tried it out yet other than compiling it, so I'm not sure it's not going to break.  https://github.com/MG-EV-Hackers/Open-Vehicle-Monitoring-System-3-MGEV/tree/feature/mg5

**Pull request closed without merging**
