### PR TITLE
Fix/est range

### PR DESCRIPTION
**Pull request by KilveEng**

### CODE REVIEW

**Comment by chrisstaite** [comment]
It's usually better to do a rebase for these kinds of updates when no one else is working on the branch

**Comment by GreyPeter** [comment]
Should I just do a 'git rebase' on my code?

**Comment by chrisstaite** [comment]
Could be the best solution?

**Comment by GreyPeter** [comment]
So do I checkout fix/est_range at my end and then do 'git rebase' or should I do it in my master branch?

**Comment by chrisstaite** [comment]
git fetch
git rebase origin/master
git push -f

**Comment by GreyPeter** [comment]
All done

**Pull request closed without merging**
